#!/usr/bin/env bash
# Transfers a file from the client to a server
# Accepts four parameters:
#                           -1- path to the file to be transferred
#                           -2- IP of the server to transfer the file to
#                           -3- username that scp connects with
#                           -4- path to the SSH private key that ''scp'' uses
# When less than 3 parameters are passed, display ''Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY''
# ''scp'' must transfer the file to the user's home directory ~/
# Strict host key checking must be disabled when using ''scp''
if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;
if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi;
