#!/usr/bin/env bash
# Configures HAproxy as a load balancer
#       uses RoundRobin
#       can be managed using the init script


# Installs HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy


# Granting permission to change files
sudo chown -R "$USER" /etc/default/haproxy
sudo chown -R "$USER" /etc/haproxy/
sudo chmod 666 /etc/haproxy/haproxy.cfg


# Enables init management
sudo echo "ENABLED=1" >> /etc/default/haproxy


# Redundancy failsafe
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg


# Configuring HAProxy
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.197.95.192:80 check\n\tserver server2 184.72.101.138:80 check\n" >> /etc/haproxy/haproxy.cfg'


# HAProxy configuration check
sudo haproxy -c -f /etc/haproxy/haproxy.cfg


sudo service haproxy restart
