#!/usr/bin/env bash
#   Create a file /var/run/myscript.pid containing the script's PID
# displays 'To infinity and beyond' indefinitely
# displays 'I hate the kill command' when receiving a 'SIGTERM' signal
# displays 'Y U no love me?!' when receiving a 'SIGINT' signal
# deletes the file /var/run/myscript.pid and terminates when receiving a 'SIGQUIT' or a 'SIGTERM'
delete() {
	rm /var/run/myscript.pid
exit
}
echo "$$" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && delete' SIGTERM
	trap 'delete' SIGQUIT
done
