#!/usr/bin/env bash
#    manipulates the 'manage_my_process'' script
# when passed the argument 'start':
#       I- Starts 'manage_my_process'
#       II- Creates a file containings its PID in '/var/run/my_process.pid'
#       III- Displays 'manage_my_process started'
# when passed the argument 'stop':
#       I- Stops 'manage_my_process'
#       II- Deletes '/var/run/my_process.pid'
#       III- Displays 'manage_my_process stopped'
# when passed the argument 'restart':
#       I- Stops manage_my_process
#       II- Deletes '/var/run/my_process.pid'
#       III- Starts 'manage_my_process'
#       IV- Creates a file containing its PID in '/var/run/my_process.pid'
#       V- Displays 'manage_my_process restarted'
# when any other, or no arguments are passed, displays 'Usage: manage_my_process {start|stop|restart}'
if [ "$1" == "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
