#!/usr/bin/env bash
#	displays the number of occurrences, IP, and HTTP status
#	sorts the visitors by number of occurrences starting by the greatest number
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
