#!/usr/bin/env bash
# configures a Ubuntu server that resolves a specified address
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/new_hosts.new
echo "127.0.0.2		localhost" > ~/new_hosts
echo "8.8.8.8		facebook.com" >> ~/new_hosts
cp -f ~/new_hosts /etc/hosts
