#!/usr/bin/env bash
# Allows the web server to run 'Nginx' as the user "nginx", and listen on 8080
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
